feat(graphing) Added absolute value and exponential graph and functions.
pie-framework/pie-lib pull request #1050
Opened 2023-12-29 10:53 UTC by akshayhiwale

Added absolute value and exponential graph and functions as per below tickets and requirements.
[https://illuminate.atlassian.net/browse/SC-27396](https://illuminate.atlassian.net/browse/SC-27396)
[https://illuminate.atlassian.net/browse/SC-27398](https://illuminate.atlassian.net/browse/SC-27398)

2024-01-02 16:16 UTC, andreeimiron approved these changes

2024-01-04 07:56 UTC, andreeapescar commented
Hi.

Please don't forget to use https://github.com/semantic-release/semantic-release for commits.

2024-01-04 07:58 UTC, andreeapescar requested changes
Please make sure you're using proper commits, as they are used in our release process to create versions and update Changelog.

2024-01-08 12:25 UTC, andreeapescar approved these changes

2024-01-08 12:25 UTC, merged