Feat(categorize,drag-in-the-blank,ica,match-list): "pool" area changes
pie-framework/pie-lib pull request #1354
Opened 2024-07-23 16:00 UTC by dianagociu

Avoid allocating more vertical space & provide a light gray fill (#ECEDF1) for the answer choice “pool” area
Screenshots are provided in the ticket:
https://illuminate.atlassian.net/browse/PD-3944

2024-07-24 13:16 UTC, andreeapescar commented
@andreeimiron can you please review this PR? You're the one who knows more about theme and I wanted to check with you if it wold be a good idea to use theme here instead.

2024-07-24 15:48 UTC, andreeimiron requested changes

2024-07-24 15:48 UTC, andreeimiron commented on packages/pie-toolbox/src/code/drag/placeholder.jsx
>      border: '1px solid #D1D1D1',
According to https://illuminate.atlassian.net/browse/PD-3849 border should be removed

2024-07-26 07:31 UTC, andreeapescar commented on packages/pie-toolbox/src/code/drag/placeholder.jsx
> +    backgroundColor: '#ECEDF1',
I introduced this new color in our colors scheme.
Let's use it.
https://github.com/pie-framework/pie-lib/blob/develop/packages/pie-toolbox/src/code/render-ui/color.js#L71

2024-07-26 09:10 UTC, merged